const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const metricOrder=['ac_input_voltage','ac_input_frequency','ac_output_voltage','ac_output_frequency','battery_charging_current','battery_discharge_current','bus_voltage','pv_input_current_for_battery','battery_voltage_from_scc'];
const labels={ac_input_voltage:'GRID VOLTAGE',ac_input_frequency:'GRID FREQUENCY',ac_output_voltage:'OUTPUT VOLTAGE',ac_output_frequency:'OUTPUT FREQUENCY',battery_charging_current:'CHARGE CURRENT',battery_discharge_current:'DISCHARGE CURRENT',bus_voltage:'DC BUS',pv_input_current_for_battery:'PV CURRENT',battery_voltage_from_scc:'SCC BATTERY'};
let refreshing=false,settingCatalog={},catalogSignature='',firmwareTools={};
const title=value=>String(value).replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase());
function reading(data,key,fallback='—'){const item=(data.readings||{})[key];if(!item||item.value===null||item.value===undefined)return fallback;return `${item.value}${item.unit?` ${item.unit}`:''}`}
function age(iso){if(!iso)return'Never';const sec=Math.max(0,Math.round((Date.now()-new Date(iso).getTime())/1000));if(sec<5)return'Just now';if(sec<60)return`${sec}s ago`;if(sec<3600)return`${Math.floor(sec/60)}m ago`;return new Date(iso).toLocaleString()}
function healthLabel(health){return({healthy:'Online',usb_missing:'Adapter missing',no_response:'No response',stale:'Data stale',warning:'Inverter warning',searching:'Searching'})[health]||'Checking'}
function protocolLabel(protocol){if(protocol==='GROWATT_MODBUS_V014')return 'Growatt Modbus RTU v0.14';if(protocol==='PI_RAW')return 'Growatt direct serial PI';return protocol}
function render(data){
  const healthy=data.health==='healthy', warning=data.health==='warning', offline=['usb_missing','no_response','stale'].includes(data.health);
  ['#top-light','#hero-light'].forEach(sel=>{$(sel).className=healthy?'healthy':offline?'offline':''});
  $('#top-status').textContent=healthLabel(data.health);$('#hero-status').textContent=data.diagnosis;$('#health-badge').textContent=healthLabel(data.health);$('#health-badge').className=`badge ${healthy?'healthy':offline?'offline':warning?'warning':'neutral'}`;
  $('#updated').textContent=data.last_success_at?`Updated ${age(data.last_success_at)}`:'Waiting for data';
  $('#pv-power').textContent=reading(data,'pv_input_power','— W');$('#pv-detail').textContent=`${reading(data,'pv_input_voltage','— V')} · ${reading(data,'pv_input_current_for_battery','— A')}`;
  $('#mode').textContent=data.mode||'Unknown';$('#temperature').textContent=`Temperature ${reading(data,'inverter_heat_sink_temperature')}`;
  $('#load-power').textContent=reading(data,'ac_output_active_power','— W');$('#load-detail').textContent=`Load ${reading(data,'ac_output_load','— %')}`;
  $('#battery').textContent=reading(data,'battery_capacity','— %');$('#battery-detail').textContent=`${reading(data,'battery_voltage','— V')} · charge ${reading(data,'battery_charging_current','— A')}`;
  const available=metricOrder.filter(key=>(data.readings||{})[key]);$('#metrics').innerHTML=available.map(key=>`<article class="metric"><small>${esc(labels[key]||key)}</small><b>${esc(reading(data,key))}</b></article>`).join('')||'<div class="empty">Live electrical measurements will appear after the inverter answers.</div>';
  $('#diagnosis-title').textContent=healthLabel(data.health);$('#diagnosis').textContent=data.diagnosis;$('#steps').innerHTML=(data.troubleshooting||[]).map(step=>`<li>${esc(step)}</li>`).join('');
  $('#device').textContent=data.device||data.configured_device||'Auto';$('#protocol').textContent=protocolLabel(data.protocol||data.configured_protocol||'Auto');$('#baud').textContent=data.baud_rate;$('#polls').textContent=data.successful_polls||0;$('#last-response').textContent=age(data.last_success_at);$('#candidates').textContent=(data.detected_devices||[]).length;
  $('#failure-count').textContent=`${data.consecutive_failures||0} consecutive failures`;$('#server-time').textContent=`App time ${new Date(data.server_time).toLocaleTimeString()} · local and private`;
  const events=data.events||[];$('#events').innerHTML=events.length?events.slice(0,30).map(item=>`<div class="event ${esc(item.level)}"><time>${new Date(item.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time><strong>${esc(item.level)}</strong><span>${esc(item.message)}</span></div>`).join(''):'<div class="empty">No connection events yet.</div>';
  renderSettings(data);
  renderFirmware(data);
}
function renderFirmware(data){
  firmwareTools=data.firmware_tools||{};const enabled=Boolean(firmwareTools.enabled),staged=firmwareTools.staged_package,versions=data.firmware||{};
  $('#firmware-state').textContent=!enabled?'Tools disabled':staged?'Package staged':'Ready';$('#firmware-state').className=`badge ${!enabled?'neutral':staged?'warning':'healthy'}`;
  const rows=Object.entries(versions);$('#firmware-versions').innerHTML=rows.length?rows.map(([key,item])=>`<div class="setting-row"><span>${esc(title(key))}</span><b>${esc(item.value??item)}</b></div>`).join(''):'<div class="empty">No CPU version has been returned yet. Keep the USB connection online and select Read versions.</div>';
  let boundary=firmwareTools.reason||'A validated file is stored only; it is never executed or sent to the inverter.';
  if(staged)boundary=`Verified ${staged.original_filename} · SHA-256 ${staged.sha256} · ${Math.round(staged.size_bytes/1024)} KB. ${boundary}`;
  $('#firmware-boundary-text').textContent=boundary;
  ['#firmware-file','#firmware-sha','#firmware-model','#stage-firmware','#firmware-url','#firmware-fetch-sha','#firmware-fetch-model','#fetch-firmware'].forEach(selector=>$(selector).disabled=!enabled);$('#read-firmware').disabled=!enabled;
}
function renderSettings(data){
  const catalog=data.setting_catalog||{}, writable=Boolean(catalog.writable);settingCatalog=catalog.items||{};
  $('#settings-lock').textContent=writable?'Commissioning enabled':'Read-only locked';$('#settings-lock').className=`badge ${writable?'warning':'healthy'}`;
  $('#safety-banner').classList.toggle('commissioning',writable);$('#safety-title').textContent=writable?'Commissioning changes enabled':'Read-only inverter access';$('#safety-detail').textContent=writable?'Every setting change requires APPLY confirmation and an inverter read-back. Return to read-only mode after commissioning.':'Monitoring is locked. Commissioning controls require two separate configuration changes and confirmation for every command.';
  const settings=data.settings||{},rows=Object.entries(settings);$('#settings-readback').innerHTML=rows.length?rows.map(([key,item])=>`<div class="setting-row"><span>${esc(title(key))}</span><b>${esc(item.value)}${item.unit?` ${esc(item.unit)}`:''}</b></div>`).join(''):'<div class="empty">Waiting for the inverter settings inquiry.</div>';
  const signature=Object.keys(settingCatalog).join('|');if(signature!==catalogSignature){catalogSignature=signature;$('#setting-key').innerHTML=Object.entries(settingCatalog).map(([key,spec])=>`<option value="${esc(key)}">${esc(spec.label)}</option>`).join('');buildSettingControl()}
  ['#setting-key','#setting-confirmation','#apply-setting'].forEach(selector=>$(selector).disabled=!writable);const control=$('#setting-value');if(control)control.disabled=!writable;
}
function buildSettingControl(){
  const key=$('#setting-key').value,spec=settingCatalog[key];if(!spec)return;let input='';
  if(spec.kind==='select')input=`<select id="setting-value">${Object.keys(spec.values).map(value=>`<option value="${esc(value)}">${esc(title(value))}</option>`).join('')}</select>`;
  else if(spec.kind==='toggle')input='<select id="setting-value"><option value="true">Enabled</option><option value="false">Disabled</option></select>';
  else input=`<input id="setting-value" type="number" inputmode="decimal" min="${spec.minimum}" max="${spec.maximum}" step="${spec.step}" value="${spec.minimum}">`;
  $('#setting-control').innerHTML=`<label><span>New value</span>${input}</label>`;$('#setting-risk').textContent=spec.risk||'Review this setting before applying it.';
}
async function refresh(){if(refreshing)return;refreshing=true;try{const response=await fetch('api/status',{cache:'no-store'});if(!response.ok)throw new Error(`Status ${response.status}`);render(await response.json())}catch(error){$('#top-status').textContent='Dashboard unavailable';$('#hero-status').textContent='The dashboard cannot reach the Growatt service yet.'}finally{refreshing=false}}
async function action(name,button){button.disabled=true;try{await fetch(`api/${name}`,{method:'POST'});setTimeout(refresh,800)}finally{setTimeout(()=>button.disabled=false,1500)}}
$('#setting-key').addEventListener('change',buildSettingControl);
$('#refresh-settings').addEventListener('click',async()=>{const button=$('#refresh-settings');button.disabled=true;$('#setting-result').textContent='Reading the current inverter profile…';try{const response=await fetch('api/settings/read',{method:'POST'}),data=await response.json();if(!response.ok)throw new Error(data.error||'Settings read failed');$('#setting-result').className='setting-result success';$('#setting-result').textContent='Current settings refreshed.';await refresh()}catch(error){$('#setting-result').className='setting-result error';$('#setting-result').textContent=error.message}finally{button.disabled=false}});
$('#settings-form').addEventListener('submit',async event=>{event.preventDefault();const button=$('#apply-setting');button.disabled=true;$('#setting-result').className='setting-result';$('#setting-result').textContent='Applying one setting and waiting for inverter read-back…';try{const response=await fetch('api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:$('#setting-key').value,value:$('#setting-value').value,confirmation:$('#setting-confirmation').value})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Setting change failed');$('#setting-result').className=`setting-result ${data.verified?'success':'error'}`;$('#setting-result').textContent=data.verified?'Setting accepted and the inverter profile was read back.':`Setting accepted, but read-back failed: ${data.verification_error||'check the Growatt display before trying again.'}`;$('#setting-confirmation').value='';await refresh()}catch(error){$('#setting-result').className='setting-result error';$('#setting-result').textContent=error.message}finally{button.disabled=false}});
$('#read-firmware').addEventListener('click',async()=>{const button=$('#read-firmware');button.disabled=true;$('#firmware-result').className='setting-result';$('#firmware-result').textContent='Reading CPU firmware versions from the inverter…';try{const response=await fetch('api/firmware/read',{method:'POST'}),data=await response.json();if(!response.ok)throw new Error(data.error||'Version inquiry failed');$('#firmware-result').className='setting-result success';$('#firmware-result').textContent='Installed firmware versions refreshed.';await refresh()}catch(error){$('#firmware-result').className='setting-result error';$('#firmware-result').textContent=error.message}finally{button.disabled=false}});
$('#firmware-form').addEventListener('submit',async event=>{event.preventDefault();const button=$('#stage-firmware'),file=$('#firmware-file').files[0];if(!file)return;button.disabled=true;$('#firmware-result').className='setting-result';$('#firmware-result').textContent='Checking package size, model, and SHA-256…';try{const max=(firmwareTools.max_package_mb||32)*1024*1024;if(file.size>max)throw new Error(`Package exceeds the configured ${firmwareTools.max_package_mb||32} MB limit`);const safeName=file.name.replace(/[^A-Za-z0-9._-]/g,'_');const response=await fetch('api/firmware/stage',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Firmware-Filename':safeName,'X-Expected-SHA256':$('#firmware-sha').value.trim(),'X-Model-Confirmation':$('#firmware-model').value.trim()},body:file}),data=await response.json();if(!response.ok)throw new Error(data.error||'Package validation failed');$('#firmware-result').className='setting-result success';$('#firmware-result').textContent='Checksum verified. The package is safely staged and has not been sent to the inverter.';await refresh()}catch(error){$('#firmware-result').className='setting-result error';$('#firmware-result').textContent=error.message}finally{button.disabled=false}});
$('#firmware-fetch-form').addEventListener('submit',async event=>{event.preventDefault();const button=$('#fetch-firmware');button.disabled=true;$('#firmware-result').className='setting-result';$('#firmware-result').textContent='Fetching from Growatt, then verifying the model, size, and SHA-256…';try{const response=await fetch('api/firmware/fetch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:$('#firmware-url').value.trim(),sha256:$('#firmware-fetch-sha').value.trim(),model_confirmation:$('#firmware-fetch-model').value.trim()})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Official package fetch failed');$('#firmware-result').className='setting-result success';$('#firmware-result').textContent='Official-domain download complete and checksum verified. The package is staged only; it was not sent to the inverter.';await refresh()}catch(error){$('#firmware-result').className='setting-result error';$('#firmware-result').textContent=error.message}finally{button.disabled=false}});
$('#poll').addEventListener('click',()=>action('poll',$('#poll')));$('#rescan').addEventListener('click',()=>action('rescan',$('#rescan')));refresh();setInterval(refresh,3000);
